### ISSUE TITLE
menu doesn't disappear after translation

### ISSUE THREAD

**Issue by Chaos99** [tomouchuu/mastodon-translate#10]
For once, the UI blocks while the translation is done, but maybe this is non-avoidable.

But for me (Chrome Version 58.0.3029.68 beta (64-bit)) on mastodon.technology
(together with https://userstyles.org/styles/139721/mastodon-variable-width)
the menu does not automatically disappear when the translation is finished.
It needs another click (carefully aimed at a non-active area) to close it.

**Comment by tomouchuu** [comment]
This should definitely be possible to do, will take a look tonight to get a fix in place

**Comment by tomouchuu** [comment]
I've pushed an update to the script (1.6.0) that will close the menu once the translation has been done. It also changes the translate toot text to loading while it's getting the translation.

Let me know if this hasn't worked for you!

**Comment by Chaos99** [comment]
Updated and works now. (Both disapppearing menu as well as (LOADING) display.)

Occasionally I get unwanted scroll-jumps after translating making it hard to find the toot or the translation.
But I can not reproduce it reliably. Probably it's new toots arriving while it's translating.
Could this update be blocked, so the translated toot does not move?
