### ISSUE TITLE
Investigate why some users are unable to save their settings

### ISSUE THREAD

**Issue by tomouchuu** [tomouchuu/mastodon-translate#8]
Have had two people reach out to me to say the script isn't working for them. Am unable to reproduce the issue on my computers/browsers. The first instance was a person's translation language not being set and the second was a person unable to set the checkbox to true to agree.

The most likely cause seems to be some sort of issue with `GM_setValue` not setting.

**Comment by tomouchuu** [comment]
Wondered if there could be a potential browser/version of tamperfork issue, nothing on the comparison chart: https://github.com/scriptish/scriptish/wiki/Comparison-Table. And had to download tamperfork on my work firefox/edge browsers and it's working there.

**Comment by tomouchuu** [comment]
Interesting, on safari tampermonkey am getting an issue with content-security-policy: `Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.` I'm not sure this is related as not even seeing the script, but could be worth considering.

**Comment by tomouchuu** [comment]
Person who is unable to set checkbox is using Windows 10 & Chrome. Had no issues on this platform at work so very confusing

**Comment by tomouchuu** [comment]
Still issue apparently 🙁

**Comment by tomouchuu** [comment]
Using a hardcoded script isn't ideal but could maybe shine a light on the script not being able to save, since if this doesn't work then I'm not sure it's an issue with setting preferences.

**Comment by hetima** [comment]
textContent of save button depends on language setting. In some cases `event.target.textContent === 'Save changes'` return false.

**Comment by tomouchuu** [comment]
Wow, this makes a ton of sense, don't see how I missed it earlier.
Will be working on this tonight, thanks @hetima !
